name: SessionTools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dask
  - h5py
  - numpy
  - pandas
  - pip
  - pytables
  - python
  - scikit-image
  - scipy
  - tifffile
  - yapf
  - ipython
  - jupyterlab
  - setuptools
  - matplotlib
  - napari
  - cloudpickle
  - pip:
      - -e .
